spring.application.name=consulta-diabete
security.jwt.secret=ARc0hrQF3vJB3e0p/GFdarwfyK/qOyP5b0ZoL5Dm28o=
security.jwt.issuer=consulta-diabete
security.jwt.exp-min=60

spring.datasource.url=jdbc:postgresql://localhost:5432/consulta-diabete
spring.datasource.username=postgres
spring.datasource.password=Senai@127
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
cht.front.url=http://localhost:5173/

cht.front.test.url=http://localhost:5173/